### ISSUE TITLE
[Feature Request]: Improve visibility on saved videos

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [PikachuEXE/FreeTube#55]
### Guidelines

- [X] I have searched the [issue tracker](https://github.com/FreeTubeApp/FreeTube/issues) for a feature request that matches the one I want to file, without success.
- [X] I have searched the [documentation](https://docs.freetubeapp.io/) for information that matches the description of the feature request I want to file, without success.

### Problem Description

There is atm no way of knowing

- If you have saved the video
- In what playlists they are saved to
- How many times it is in the list u are adding it to

Hover over thumbnail doenst give u any info and the add to playlist prompt also doesnt give u any info about this. Im not saying it should be presented at those places but it would make the most sense to me because in those views users will be in when they are about to add a video.

### Proposed Solution

TBH i have know idea what a possible implementation looks like. Maybe somebody else can chime in on this.

### Alternatives Considered

None.

### Issue Labels

display more information to user, visual improvement

### Additional Information

Not sure if we have to address this before v1

**Comment by toby63** [comment]
IMHO the "old" star symbol was already quite perfect.
As I outlined in #65 a double-click on the star symbol could open a menu so you could add a video to a second playlist etc.

This menu could then include seperate star symbols, that indicate in which playlists the video is already included.

Additionally a small field below the star symbol (on the video page) could indicate in how many or in what playlists the video is already included.
Or it could open a small field that shows this info, so it is more hidden.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Star icon is back so https://github.com/FreeTubeApp/FreeTube/pull/4561 fully closes this

**Comment by toby63** [comment]
@efb4f5ff-1298-471a-8973-3d47447115dc I disagree a bit, because:
AFAIK
1. The star icon is only activated if it was used to add a video to the "standard" playlist.
2. https://github.com/FreeTubeApp/FreeTube/pull/4561 only adds indicators to the "add-menu" not the regular view on the video page, the overview pages etc.

My idea would have been that:
a) the star symbole indicates whether a video was already added to any playlist (on every relevant page: video, playlists, subscriptions etc.).
b) additional info would be shown (or expandable) in which playlists the video already exits (on every relevant page).

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
A) This isnt how the star symbol is intended to be used. It is intended to be used to be the same as YT's solution so this isnt going to be changed.
B) It doesnt make sense to add it in every other page because the only time you need that info is when you are going to add it to a playlist

**Comment by toby63** [comment]
> A) This isnt how the star symbol is intended to be used. It is intended to be used to be the same as YT's solution so this isnt going to be changed. 

Ok, I of course respect your design choice, but I would 1) not always do everything the same way youtube does, 2) Rethink whether the symbols really make sense this way.
But anyway, a seperate symbole would then be my second proposal.

> B) It doesnt make sense to add it in every other page because the only time you need that info is when you are going to add it to a playlist

I disagree, because UX wise, it takes you longer to identify in which playlists a video is included, as you have to open the "add-menu" first.
To maintain a reasonable size etc., it would be useful to at least show the name of the first playlist that a video was added to.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
this is resolved

**Comment by toby63** [comment]
> this is resolved

Where is this resolved?
I use latest master and there is no indicator.
See also: https://github.com/FreeTubeApp/FreeTube/issues/4982

**Comment by absidue** [comment]
@toby63 It is solved, the quick bookmark icon turns into a check mark when the video is saved to the quick bookmark playlist.
